// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	minio "github.com/minio/minio-go/v7"

	mock "github.com/stretchr/testify/mock"
)

// FileStorage is an autogenerated mock type for the FileStorage type
type FileStorage struct {
	mock.Mock
}

// GeneratePresignedURL provides a mock function with given fields: ctx, bucketName, objectName
func (_m *FileStorage) GeneratePresignedURL(ctx context.Context, bucketName string, objectName string) (string, error) {
	ret := _m.Called(ctx, bucketName, objectName)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, bucketName, objectName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, bucketName, objectName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucketName, objectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, fileName, content, size, isResult
func (_m *FileStorage) Upload(ctx context.Context, fileName string, content io.Reader, size int64, isResult bool) (string, error) {
	ret := _m.Called(ctx, fileName, content, size, isResult)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, bool) (string, error)); ok {
		return rf(ctx, fileName, content, size, isResult)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, bool) string); ok {
		r0 = rf(ctx, fileName, content, size, isResult)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, bool) error); ok {
		r1 = rf(ctx, fileName, content, size, isResult)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadByChunks provides a mock function with given fields: ctx, fileName, content, size, uploadID, partID
func (_m *FileStorage) UploadByChunks(ctx context.Context, fileName string, content io.Reader, size int64, uploadID string, partID int) (string, error) {
	ret := _m.Called(ctx, fileName, content, size, uploadID, partID)

	if len(ret) == 0 {
		panic("no return value specified for UploadByChunks")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string, int) (string, error)); ok {
		return rf(ctx, fileName, content, size, uploadID, partID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string, int) string); ok {
		r0 = rf(ctx, fileName, content, size, uploadID, partID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, string, int) error); ok {
		r1 = rf(ctx, fileName, content, size, uploadID, partID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFinish provides a mock function with given fields: ctx, fileName, uploadID, parts
func (_m *FileStorage) UploadFinish(ctx context.Context, fileName string, uploadID string, parts []minio.CompletePart) (string, error) {
	ret := _m.Called(ctx, fileName, uploadID, parts)

	if len(ret) == 0 {
		panic("no return value specified for UploadFinish")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []minio.CompletePart) (string, error)); ok {
		return rf(ctx, fileName, uploadID, parts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []minio.CompletePart) string); ok {
		r0 = rf(ctx, fileName, uploadID, parts)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []minio.CompletePart) error); ok {
		r1 = rf(ctx, fileName, uploadID, parts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadInit provides a mock function with given fields: ctx, fileName
func (_m *FileStorage) UploadInit(ctx context.Context, fileName string) (string, error) {
	ret := _m.Called(ctx, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadInit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, fileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileStorage creates a new instance of FileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileStorage {
	mock := &FileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
