// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "dpsystem/domain"

	mock "github.com/stretchr/testify/mock"
)

// MediaProviderRepository is an autogenerated mock type for the MediaProviderRepository type
type MediaProviderRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MediaProviderRepository) CreateTask(ctx context.Context, task *domain.MediaTask) (uint, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MediaTask) (uint, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MediaTask) uint); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.MediaTask) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: ctx, id
func (_m *MediaProviderRepository) GetTaskByID(ctx context.Context, id uint64) (*domain.MediaTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *domain.MediaTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.MediaTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.MediaTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MediaTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveTask provides a mock function with given fields: ctx, task
func (_m *MediaProviderRepository) SaveTask(ctx context.Context, task *domain.MediaTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for SaveTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MediaTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusAndResultPath provides a mock function with given fields: ctx, id, status, resultPath
func (_m *MediaProviderRepository) UpdateStatusAndResultPath(ctx context.Context, id uint64, status string, resultPath string) error {
	ret := _m.Called(ctx, id, status, resultPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAndResultPath")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) error); ok {
		r0 = rf(ctx, id, status, resultPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMediaProviderRepository creates a new instance of MediaProviderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaProviderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaProviderRepository {
	mock := &MediaProviderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
