// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	constants "dpsystem/internal/constants"

	io "io"

	minio "github.com/minio/minio-go/v7"

	mock "github.com/stretchr/testify/mock"
)

// MediaProviderService is an autogenerated mock type for the MediaProviderService type
type MediaProviderService struct {
	mock.Mock
}

// ChangeResultPath provides a mock function with given fields: ctx, taskID, path
func (_m *MediaProviderService) ChangeResultPath(ctx context.Context, taskID uint64, path string) error {
	ret := _m.Called(ctx, taskID, path)

	if len(ret) == 0 {
		panic("no return value specified for ChangeResultPath")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = rf(ctx, taskID, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeTaskStatus provides a mock function with given fields: ctx, taskID, status
func (_m *MediaProviderService) ChangeTaskStatus(ctx context.Context, taskID uint64, status string) error {
	ret := _m.Called(ctx, taskID, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTaskStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = rf(ctx, taskID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadByChunks provides a mock function with given fields: ctx, fileName, content, size, uploadID, partID
func (_m *MediaProviderService) UploadByChunks(ctx context.Context, fileName string, content io.Reader, size int64, uploadID string, partID int) (string, error) {
	ret := _m.Called(ctx, fileName, content, size, uploadID, partID)

	if len(ret) == 0 {
		panic("no return value specified for UploadByChunks")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string, int) (string, error)); ok {
		return rf(ctx, fileName, content, size, uploadID, partID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string, int) string); ok {
		r0 = rf(ctx, fileName, content, size, uploadID, partID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, string, int) error); ok {
		r1 = rf(ctx, fileName, content, size, uploadID, partID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFinish provides a mock function with given fields: ctx, fileName, size, action, uploadID, parts, taskID
func (_m *MediaProviderService) UploadFinish(ctx context.Context, fileName string, size int64, action constants.VideoAction, uploadID string, parts []minio.CompletePart, taskID uint64) error {
	ret := _m.Called(ctx, fileName, size, action, uploadID, parts, taskID)

	if len(ret) == 0 {
		panic("no return value specified for UploadFinish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, constants.VideoAction, string, []minio.CompletePart, uint64) error); ok {
		r0 = rf(ctx, fileName, size, action, uploadID, parts, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadInit provides a mock function with given fields: ctx, fileName
func (_m *MediaProviderService) UploadInit(ctx context.Context, fileName string) (uint, string, error) {
	ret := _m.Called(ctx, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadInit")
	}

	var r0 uint
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint, string, error)); ok {
		return rf(ctx, fileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint); ok {
		r0 = rf(ctx, fileName)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, fileName)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, fileName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMediaProviderService creates a new instance of MediaProviderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaProviderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaProviderService {
	mock := &MediaProviderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
